# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mariadb
    container_name: youbetsportdb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: password
    ports:
        - 3306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
