<?php

namespace Dwf\PronosticsBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Dwf\PronosticsBundle\Entity;

/**
 * BestScorerPronosticRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BestScorerPronosticRepository extends EntityRepository
{
    public function findOneByUserAndEvent(\Dwf\PronosticsBundle\Entity\User $user, \Dwf\PronosticsBundle\Entity\Event $event)
    {
        $qb = $this->createQueryBuilder('b')
        ->where('b.user = :user')
        //->where('p.expires_at > :date')
        ->setParameter('user', $user)
        ->andWhere('b.event = :event')
        ->setParameter('event', $event)
        ;
    
        $query = $qb->getQuery();
        return $query->getResult();
    }
}
