<?php

namespace Dwf\PronosticsBundle\Entity;

/**
 * ContestMessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContestMessageRepository extends \Doctrine\ORM\EntityRepository
{
}
