<?php

namespace Dwf\PronosticsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends EntityRepository
{
    public function findAllOrderedByDate()
    {
        $qb = $this->createQueryBuilder('e')
        ->where('e.active = 1')
        ->orderBy('e.startDate', 'ASC');
    
        $query = $qb->getQuery();
        return $query->getResult();
    }
}
