<?php

namespace Dwf\PronosticsBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Dwf;

/**
 * GameTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GameTypeRepository extends EntityRepository
{
	public function findAllByEvent(Dwf\PronosticsBundle\Entity\Event $event)
	{
		$qb = $this->createQueryBuilder('g')
			->join('g.events', 'eg')
			->where('eg.id IN (:event)')
			->setParameter('event', $event)
		;
	
		$query = $qb->getQuery();
		return $query->getResult();
	}
	
	public function getByEventAndPosition(Dwf\PronosticsBundle\Entity\Event $event, $position)
	{
		$qb = $this->createQueryBuilder('g')
		->join('g.events', 'eg')
		->where('eg.id IN (:event)')
		->setParameter('event', $event)
		->andWhere('g.position = :position')
		->setParameter('position', $position)
		;
	
		$query = $qb->getQuery();
		return $query->getResult();
	}
    
    public function getFirstByEvent(Dwf\PronosticsBundle\Entity\Event $event)
    {
        $qb = $this->createQueryBuilder('g')
        ->join('g.events', 'eg')
        ->where('eg.id IN (:event)')
        ->setParameter('event', $event)
        ->addOrderBy('g.position', 'ASC')
        ->setMaxResults(1)
        ;
    
        $query = $qb->getQuery();
        return $query->getResult();
    }
}
