<?php

namespace Dwf\PronosticsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PlayerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlayerRepository extends EntityRepository
{
	public function findAllOrderedByName()
	{
		$qb = $this->createQueryBuilder('p')
		->orderBy('p.name', 'ASC');
	
		$query = $qb->getQuery();
		return $query->getResult();
	}
}
