<?php

namespace Dwf\PronosticsBundle\Entity;

/**
 * SliceScoreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SliceScoreRepository extends \Doctrine\ORM\EntityRepository
{
}
