<?php

namespace Dwf\PronosticsBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Dwf;

/**
 * StandingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StandingRepository extends EntityRepository
{
    public function findByUserAndEvent(Dwf\PronosticsBundle\Entity\User $user, Dwf\PronosticsBundle\Entity\Event $event)
    {
        $qb = $this->createQueryBuilder('s')
        ->where('s.user = :user')
        ->setParameter('user', $user)
        ->andWhere('s.event = :event')
        ->setParameter('event', $event)
        ;
        $query = $qb->getQuery();
        return $query->getResult();
    }
}
