<?php

namespace Dwf\PronosticsBundle\Entity;

use Doctrine\ORM\EntityRepository;


/**
 * PronosticRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function getGameProno($game_id)
    {
        $qb = $this->createQueryBuilder('p')
        ->where('p.user = :user')
        //->where('p.expires_at > :date')
        ->setParameter('user', $user)
        //->orderBy('p.expiresAt', 'DESC');
        ;
        $query = $qb->getQuery();
        return $query->getResult();
    }
    
    public function findByUsername($username)
    {
        $qb = $this->createQueryBuilder('u')
        ->where('u.username = :username')
        //->where('p.expires_at > :date')
        ->setParameter('username', $username)
        //->orderBy('p.expiresAt', 'DESC');
        ;
        $query = $qb->getQuery();
        return $query->getResult();
    }
}
