<?php

namespace Dwf\PageBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageRepository extends EntityRepository
{
    public function getActivePages()
    {
        $qb = $this->createQueryBuilder('p')
        ->where('p.active = 1')
        ->orderBy('p.id', 'DESC');
        $query = $qb->getQuery();
        return $query->getResult();
    }
}
