<?php

namespace Dwf\PronosticsBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AdminMessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdminMessageRepository extends EntityRepository
{
}
