<?php

namespace Dwf\PronosticsBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AdminMessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdminMessageRepository extends EntityRepository
{
    public function findLast()
    {
        $qb = $this->createQueryBuilder('a')
                    ->orderBy('a.date', 'DESC')
                    ->setMaxResults(1)
        ;
        $query = $qb->getQuery();
        return $query->getOneOrNullResult();
    }
}
